# Generated by Django 2.2b1 on 2019-02-16 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_album'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=250)),
                ('song_title', models.CharField(max_length=500)),
                ('genre', models.CharField(max_length=100)),
                ('song_logo', models.CharField(max_length=1000)),
            ],
        ),
    ]
