# Generated by Django 2.2b1 on 2019-02-16 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_year',
            field=models.IntegerField(default=1992),
        ),
    ]
