# Generated by Django 2.2b1 on 2019-02-16 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_song_song_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=250)),
                ('photo_title', models.CharField(max_length=500)),
                ('genre', models.CharField(max_length=100)),
                ('photo_year', models.IntegerField(default=1992)),
            ],
        ),
    ]
